<?php


use App\Models\Branch;
use App\Models\Coordinate;
use App\Models\DistanceCalculator;
use App\Models\Place;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;
use Tests\TestCase;

class DistanceCalculatorTest extends TestCase
{
    use LazilyRefreshDatabase;

    private Place|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model $to;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->branch = Branch::factory()->create([
            'latitude' => 14.56580550,
            'longitude' => 121.01148240
        ]);
        $this->to = Place::factory()->create([
            'latitude' => 14.563716099999997,
            'longitude' => 121.0104251
        ]);
    }

    /** @test */
    public function it_can_calculate_distance(): void
    {
        $to = new Coordinate($this->to->longitude, $this->to->latitude);
        $from = new Coordinate($this->branch->longitude, $this->branch->latitude);
        $distance = (new DistanceCalculator($from, $to))->calculate();
        $this->assertEquals(259, $distance);
    }
}
