<?php

namespace Tests\Unit;

use App\Models\SalaryCalculator;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;
use Illuminate\Support\Carbon;
use SebastianBergmann\Complexity\Calculator;
use Tests\TestCase;

class SalaryCalculatorTest extends TestCase
{
    use LazilyRefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->staff = $this->staff();
//        $this->calculator = new FakeSalaryCalculator($this->staff);
    }

    /** @test */
    public function salary_day_is_on_15th_and_last_day_of_the_month(): void
    {
        $fifteen = Carbon::parse('2023-11-15');
        Carbon::setTestNow($fifteen);
        $calculator = new FakeSalaryCalculator($this->staff);
        $this->assertEquals(15, $calculator->firstSalaryDay());

        $lastDay = Carbon::parse('2023-11-30');
        Carbon::setTestNow($lastDay);
        $calculator = new FakeSalaryCalculator($this->staff);
        $this->assertEquals(30, $calculator->secondSalaryDay());
    }

    /** @test */
    public function if_salary_day_falls_on_weekend_any_week_days_before_is_salary_day(): void
    {
        $sunday = Carbon::parse('2023-10-15');
        Carbon::setTestNow($sunday);
        $calculator = new FakeSalaryCalculator($this->staff);
        $this->assertEquals(13, $calculator->firstSalaryDay());

        $saturday = Carbon::parse('2023-09-30');
        Carbon::setTestNow($saturday);
        $calculator = new FakeSalaryCalculator($this->staff);
        $this->assertEquals(29, $calculator->secondSalaryDay());
    }

    /** @test */
    public function if_salary_day_falls_on_holiday_a_day_before_should_be_salary_day(): void
    {
        $this->assertTrue(true);
    }
}

class FakeSalaryCalculator extends SalaryCalculator
{
    public function isSalaryDay()
    {
        return $this->salaryDay();
    }

    public function firstSalaryDay()
    {
        return $this->firstSalaryDay;
    }

    public function secondSalaryDay()
    {
        return $this->secondSalaryDay;
    }
}
